### ISSUE TITLE
Remove intermediate pipeline file "pipe.yml"

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter-delete#11]
https://github.com/byu-dml/d3m-experimenter/blob/9b3ea6722c1f13dfbf01bfdc803f34714d302557/experimenter/experimenter.py#L284

Is writing a temporary pipeline to disk necessary? Can we just keep it in memory?

**Comment by orionw** [comment]
Changed in pull request.
